/*
 * Copyright (C) 2014 Hedgehog01.
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 2.1 of the License, or (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with this library; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston,
 * MA 02110-1301  USA
 */
package com.jjlcollectors.collectables.windows;

/**
 *
 * @author Hedgehog01
 */
public class AddCoin extends javax.swing.JPanel
{

    /**
     * Creates new form AddCoin
     */
    public AddCoin()
    {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        CollectionDBPUEntityManager = java.beans.Beans.isDesignTime() ? null : javax.persistence.Persistence.createEntityManagerFactory("CollectionDBPU").createEntityManager();
        coinInfoQuery = java.beans.Beans.isDesignTime() ? null : CollectionDBPUEntityManager.createQuery("SELECT c FROM CoinInfo c");
        coinInfoList = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : coinInfoQuery.getResultList();
        jTextFieldCoinName = new javax.swing.JTextField();
        jTextFieldCoinGrade = new javax.swing.JTextField();
        jTextFieldCoinFaceValue = new javax.swing.JTextField();
        jTextFieldCoinBuyPrice = new javax.swing.JTextField();
        jTextFieldCoinValue = new javax.swing.JTextField();
        jTextMintMark = new javax.swing.JTextField();
        jTextCoinYear = new javax.swing.JTextField();
        jTextFieldCoinNote = new javax.swing.JTextField();
        jLabelCoinName = new javax.swing.JLabel();
        jLabelCoinGrade = new javax.swing.JLabel();
        jLabelCoinFaceValue = new javax.swing.JLabel();
        jLabelCoinCurrency = new javax.swing.JLabel();
        jLabelCoinBuyPrice = new javax.swing.JLabel();
        jLabelCoinValue = new javax.swing.JLabel();
        jLabelCoinMintMark = new javax.swing.JLabel();
        jLabelCoinMintYear = new javax.swing.JLabel();
        jLabelCoinNote = new javax.swing.JLabel();
        jComboBoxCoinCurrency = new javax.swing.JComboBox();

        jTextFieldCoinName.setText("Name");
        jTextFieldCoinName.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jTextFieldCoinNameActionPerformed(evt);
            }
        });

        jTextFieldCoinGrade.setText("Grade");
        jTextFieldCoinGrade.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jTextFieldCoinGradeActionPerformed(evt);
            }
        });

        jTextFieldCoinFaceValue.setText("Face value");

        jTextFieldCoinBuyPrice.setText("Buy Price");

        jTextFieldCoinValue.setText("Estimated Value");

        jTextMintMark.setText("Mint Mark");

        jTextCoinYear.setText("Coin Year");

        jTextFieldCoinNote.setText("More info");
        jTextFieldCoinNote.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jTextFieldCoinNoteActionPerformed(evt);
            }
        });

        jLabelCoinName.setText("Coin Name");

        jLabelCoinGrade.setText("Coin Grade");

        jLabelCoinFaceValue.setText("Coin Face Value");

        jLabelCoinCurrency.setText("Coin name");

        jLabelCoinBuyPrice.setText("Coin Buy Price");

        jLabelCoinValue.setText("Coin Value");

        jLabelCoinMintMark.setText("Coin Mint Mark");

        jLabelCoinMintYear.setText("Coin Mint Year");

        jLabelCoinNote.setText("More info");

        jComboBoxCoinCurrency.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        org.jdesktop.beansbinding.ELProperty eLProperty = org.jdesktop.beansbinding.ELProperty.create("${}");
        org.jdesktop.swingbinding.JComboBoxBinding jComboBoxBinding = org.jdesktop.swingbinding.SwingBindings.createJComboBoxBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, coinInfoList, eLProperty, jComboBoxCoinCurrency);
        bindingGroup.addBinding(jComboBoxBinding);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(91, 91, 91)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelCoinBuyPrice)
                            .addComponent(jLabelCoinValue)
                            .addComponent(jLabelCoinMintMark)
                            .addComponent(jLabelCoinMintYear)
                            .addComponent(jLabelCoinNote))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextCoinYear)
                            .addComponent(jTextFieldCoinBuyPrice)
                            .addComponent(jTextFieldCoinValue, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                            .addComponent(jTextMintMark)
                            .addComponent(jTextFieldCoinNote)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelCoinName, javax.swing.GroupLayout.DEFAULT_SIZE, 142, Short.MAX_VALUE)
                            .addComponent(jLabelCoinGrade, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabelCoinFaceValue, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelCoinCurrency)
                                .addGap(0, 92, Short.MAX_VALUE)))
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextFieldCoinName)
                            .addComponent(jTextFieldCoinGrade)
                            .addComponent(jTextFieldCoinFaceValue)
                            .addComponent(jComboBoxCoinCurrency, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(87, 87, 87))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(89, 89, 89)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelCoinGrade)
                        .addGap(52, 52, 52))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldCoinName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelCoinName))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldCoinGrade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldCoinFaceValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelCoinFaceValue))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jComboBoxCoinCurrency, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelCoinCurrency))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 83, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTextFieldCoinBuyPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldCoinValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextMintMark, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextCoinYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldCoinNote, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabelCoinBuyPrice)
                                            .addGap(26, 26, 26))
                                        .addComponent(jLabelCoinValue))
                                    .addGap(26, 26, 26))
                                .addComponent(jLabelCoinMintMark))
                            .addGap(26, 26, 26))
                        .addComponent(jLabelCoinMintYear))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(110, 110, 110)
                        .addComponent(jLabelCoinNote)))
                .addContainerGap())
        );

        bindingGroup.bind();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldCoinGradeActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jTextFieldCoinGradeActionPerformed
    {//GEN-HEADEREND:event_jTextFieldCoinGradeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCoinGradeActionPerformed

    private void jTextFieldCoinNameActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jTextFieldCoinNameActionPerformed
    {//GEN-HEADEREND:event_jTextFieldCoinNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCoinNameActionPerformed

    private void jTextFieldCoinNoteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCoinNoteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCoinNoteActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.persistence.EntityManager CollectionDBPUEntityManager;
    private java.util.List<com.jjlcollectors.collectables.windows.CoinInfo> coinInfoList;
    private javax.persistence.Query coinInfoQuery;
    private javax.swing.JComboBox jComboBoxCoinCurrency;
    private javax.swing.JLabel jLabelCoinBuyPrice;
    private javax.swing.JLabel jLabelCoinCurrency;
    private javax.swing.JLabel jLabelCoinFaceValue;
    private javax.swing.JLabel jLabelCoinGrade;
    private javax.swing.JLabel jLabelCoinMintMark;
    private javax.swing.JLabel jLabelCoinMintYear;
    private javax.swing.JLabel jLabelCoinName;
    private javax.swing.JLabel jLabelCoinNote;
    private javax.swing.JLabel jLabelCoinValue;
    private javax.swing.JTextField jTextCoinYear;
    private javax.swing.JTextField jTextFieldCoinBuyPrice;
    private javax.swing.JTextField jTextFieldCoinFaceValue;
    private javax.swing.JTextField jTextFieldCoinGrade;
    private javax.swing.JTextField jTextFieldCoinName;
    private javax.swing.JTextField jTextFieldCoinNote;
    private javax.swing.JTextField jTextFieldCoinValue;
    private javax.swing.JTextField jTextMintMark;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables


}
