/*
 * Enumeration class CoinCurrency - represents coin grades.
 * @author Nathan Randelman
 * @version 15.09.2014
 */

package com.jjlcollectors.collectables.coins;

/**
 *
 * @author nathanr
 */
public enum CoinCurrency {
    UNKNOWN,ABKHAZIAN_APSAR,RUSSIAN_RUBLE,AFGHAN_AFGHANI,EURO,ALBANIAN_LEK,ALDERNEY_POUND,TUNISIAN_DINAR,TURKMENISTAN_MANAT,TUVALUAN_DOLLAR,UGANDAN_SHILLING,UKRAINIAN_HRYVNIA,UNITED_ARAB_EMIRATES_DIRHAM,URUGUAYAN_PESO,UZBEKISTANI_SOM,VANUATU_VATU,VENEZUELAN_BOLÍVAR,VIETNAMESE_ĐỒNG,YEMENI_RIAL,ZAMBIAN_KWACHA




}
